name: Security Checks

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Analyze CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          fail-on-error: true

      - name: Dependency Review
        uses: github/dependency-review-action@v2
        with:
          fail-on-severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
      - name: Run git-secrets
        run: |
          git secrets --register-aws
          git secrets --scan
